# Generated by Django 2.2.4 on 2020-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='Main.Quiz'),
        ),
    ]
