# Generated by Django 2.2.4 on 2020-04-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200427_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Question_Thumbnails'),
        ),
    ]
