# Generated by Django 2.2.4 on 2020-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_quiz_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='user', to='Main.Quiz'),
        ),
    ]
