# Generated by Django 2.2.4 on 2020-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200427_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
