# Generated by Django 2.2.4 on 2020-05-05 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0013_auto_20200505_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='likes',
        ),
        migrations.AddField(
            model_name='quiz',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
