# Generated by Django 2.2.4 on 2020-05-14 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0014_auto_20200505_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, related_name='completed_quizzes', to='Main.Quiz'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
