# Generated by Django 2.2.4 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20200514_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='User_Banners'),
        ),
    ]
