# Generated by Django 2.2.4 on 2020-05-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_completedquiz_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedquiz',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
