# Generated by Django 2.2.4 on 2020-05-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20200515_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquiz',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
