# Generated by Django 2.2.4 on 2020-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_completedquiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
